{{- if .Values.prometheusConfig.enabled -}}
{{- $namespace := .Release.Namespace -}}
{{- $name := .Values.prometheusConfig.additionalScrapeConfigs.name -}}
  {{- if not $name -}}
  {{- $name = printf "%s-additional-scrape-configs" (include "ydb-prometheus.fullname" $) -}}
  {{- end -}}
  {{- $data := include "ydb-prometheus.externalCluster.config" $ -}}
  {{- if $data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $namespace }}
  labels:
{{- include "ydb-prometheus.labels" $ | nindent 4 }}
data:
  {{ .Values.prometheusConfig.additionalScrapeConfigs.key }}: {{ $data | b64enc | quote }}
  {{- end -}}
{{- end -}}